# This is a basic workflow to help you get started with Actions

name: Mysql Test

on:
  push:
    branches: [ master ]

jobs:
  run-mvn-test:

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        distribution: [ 'microsoft' ]
        version: [ '17' ]

    name: ${{ matrix.distribution }} ${{ matrix.version }} (jdk-x64) - ${{ matrix.os }} - Test

    runs-on: ${{ matrix.os }}

    env:
      DB_DATABASE: test_db
      DB_USER: root
      DB_PASSWORD: root

steps:
  - name: Set up MySQL
    run: |
      sudo /etc/init.d/mysql start
      mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}    steps:
