# This is a basic workflow to help you get started with Actions

name: Mysql CI

on:
  push:
    branches: [ master ]

jobs:
  run-mvn-test:

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        distribution: [ 'microsoft' ]
        version: [ '17' ]

    name: ${{ matrix.distribution }} ${{ matrix.version }} (jdk-x64) - ${{ matrix.os }} - Test

    runs-on: ${{ matrix.os }}

    env:
      DB_DATABASE: job_scheduler
      DB_USER: root
      DB_PASSWORD: root
    steps:
      - name: Set up MySQL 8
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}

      - name: Checkout Sourse Code
        uses: actions/checkout@v2.4.0

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.version }}
          distribution: ${{ matrix.distribution }}

      - name: Mvn Test
        run: mvn test -Dspring.profiles.active=test